### ISSUE TITLE
BUG: Inline docs tooltip doesn't show when the IDE is open in the drawer

### ISSUE THREAD

**Issue by jasonbahl** [wp-graphql/wpgraphql-ide#108]
When hovering over a field in a document, we should see a tooltip/popover with some documentation from the Schema about that field. 

for example: 

![CleanShot 2024-04-16 at 12 38 58](https://github.com/wp-graphql/wpgraphql-ide/assets/1260765/2655263f-8ff6-4979-ad32-9dc992945370)

However when the IDE is opened in the drawer, the tooltip/popover is not visible. 

![CleanShot 2024-04-16 at 12 39 15](https://github.com/wp-graphql/wpgraphql-ide/assets/1260765/6afab3a5-f614-41d2-b7c1-4fc59adc4cc8)

My hunch is that this is a z-index issue.

(related: #74)

**Comment by josephfusco** [comment]
Closed by https://github.com/wp-graphql/wpgraphql-ide/releases/tag/v1.1.7
