### ISSUE TITLE
Pluggable APIs

### ISSUE THREAD

**Issue by josephfusco** [wp-graphql/wpgraphql-ide#109]
Modify and Save Query Document

## UI Pluggable Areas

- [x] #110
- [ ] #111
- [ ] #112
- [x] #113
- [ ] #114
- [ ] #115
- [ ] #116
- [ ] #117

## Public State

- [ ] #118
- [ ] #119
- [ ] #120
- [x] #121
- [ ] #122
- [ ] #123

**Comment by jasonbahl** [comment]
Closing this issue as the issues are now under the "Memo: Pluggable APIs" workstream in the project board and no longer require this issue to be used for central tracking.
