### ISSUE TITLE
Plugin Review Feedback

### ISSUE THREAD

**Issue by josephfusco** [wp-graphql/wpgraphql-ide#189]
This issue tracks all of the feedback received from the WordPress.org plugin review team.

- [ ] #190
- [ ] #191
- [ ] #192
- [ ] #193
- [ ] #194
- [ ] #195
- [ ] #196

**Comment by jasonbahl** [comment]
Closing this issue as all issues are now tracked within the project board under the "WordPress.org Feedback" working stream.
