### ISSUE TITLE
Document public resource for compressed content

### ISSUE THREAD

**Issue by josephfusco** [wp-graphql/wpgraphql-ide#190]
> "In reviewing your plugin, we cannot find a non-compiled version of your javascript and/or css related source code."

## Acceptance Criteria
   - The plugin's `readme.txt` must contain documentation or links to the non-compressed source code for all included JavaScript and CSS files.

## Tasks
   - Include the source code for all compressed JavaScript and CSS files in your plugin.
   - If using external libraries, provide a link to the non-compressed developer libraries in your `readme.txt` file.
   - Ensure the `readme.txt` clearly documents the location of the source code or the link.

**Comment by jasonbahl** [comment]
closed by #199
