### ISSUE TITLE
Avoid Using HEREDOC or NOWDOC Syntax

### ISSUE THREAD

**Issue by josephfusco** [wp-graphql/wpgraphql-ide#192]
> "Do not use HEREDOC or NOWDOC syntax in your plugins."

## Acceptance Criteria
   - The plugin must not contain any HEREDOC or NOWDOC syntax; all such instances should be replaced with compliant code.

## Tasks
   - Identify all instances of HEREDOC or NOWDOC syntax in your plugin.
   - Refactor the code to use alternative methods of outputting content that comply with WordPress guidelines.

**Comment by jasonbahl** [comment]
closed by #199
