### ISSUE TITLE
Remove Remote File Calls

### ISSUE THREAD

**Issue by josephfusco** [wp-graphql/wpgraphql-ide#193]
> "Offloading images, js, css, and other scripts to your servers or any remote service (like Google, MaxCDN, jQuery.com etc) is disallowed."

## Acceptance Criteria
   - The plugin should not call any remote files except those permitted by WordPress guidelines (e.g., Google Fonts).

## Tasks
   - Identify all instances where the plugin calls external files.
   - Replace these calls by including the files locally within the plugin.

**Comment by josephfusco** [comment]
There are no remote files / CDNs being used.

**Comment by jasonbahl** [comment]
closed by #199
