### ISSUE TITLE
Escape Variables and Options When Echoed

### ISSUE THREAD

**Issue by josephfusco** [wp-graphql/wpgraphql-ide#194]
> "All variables that are echoed need to be escaped when they're echoed."

## Acceptance Criteria
   - All echoed variables and options in the plugin must be properly escaped using appropriate WordPress functions.

## Tasks
   - Review all instances in the plugin where variables, options, or generated data are echoed.
   - Ensure proper escaping of all variables when they are outputted, using the appropriate `esc_*()` functions.

**Comment by jasonbahl** [comment]
closed by #199
