### ISSUE TITLE
Ensure Unique Function/Class/Namespace Names

### ISSUE THREAD

**Issue by josephfusco** [wp-graphql/wpgraphql-ide#195]
> "All plugins must have unique function names, namespaces, defines, class and option names."

## Acceptance Criteria
   - All function names, class names, defines, and namespaces must be unique to the plugin, avoiding conflicts with other plugins or WordPress core functions.

## Tasks
   - Review and update function names, class names, defines, and namespaces in the plugin to ensure they are unique.
   - Use a distinctive prefix that is specific to your plugin.

**Comment by josephfusco** [comment]
This one seems complete as the entire wpgraphql-ide.php file is using
```php
namespace WPGraphQLIDE;
```

**Comment by jasonbahl** [comment]
closed by #199
