### ISSUE TITLE
Public user query seems to stay authenticated

### ISSUE THREAD

**Issue by josephfusco** [wp-graphql/wpgraphql-ide#202]
As a WPGraphQL IDE user, I expect the public user query to not include auth headers. Currently, toggling the authenticated user button shows the same behavior for both authenticated and not authenticated.

WPGraphQL IDE version 2.1.5 is confirmed to be broken.

## Acceptance Criteria

- [ ] Public user requests do not show authenticated data
- [ ] Tests are updated to include coverage for this regression 

### Authenticated request

![CleanShot 2024-09-11 at 14 08 29@2x](https://github.com/user-attachments/assets/a1e896cd-434f-4759-bcda-6842d101b171)

### Public user request

![CleanShot 2024-09-11 at 14 09 28@2x](https://github.com/user-attachments/assets/315b9450-f547-4b91-9ff9-8b7deb9238f0)

**Comment by jasonbahl** [comment]
@josephfusco I believe this was resolved, eh?

**Comment by jasonbahl** [comment]
ah yes, closed by: https://github.com/wp-graphql/wpgraphql-ide/pull/201
