### ISSUE TITLE
Implement Changesets

### ISSUE THREAD

**Issue by jasonbahl** [wp-graphql/wpgraphql-ide#21]
As a WPGraphQL plugin contributor, I want to create a release workflow that leverages changesets in order to assist with scheduling releases and mitigate human error.

## Acceptance Criteria

- changeset framework is implemented in the wpgraphql-ide repo with minimal disruption to existing workflows
- changeset markdown file is created via GitHub label
- changeset markdown file description uses the semantic PR title
- updating the PR title updates the changeset markdown file

## Technical Details

- Prior Art - https://github.com/wpengine/wp-graphql-content-blocks
- Changesets - https://github.com/changesets/changesets
- Original Jira ticket for adding changesets to wp-graphql-content-blocks - https://wpengine.atlassian.net/browse/MERL-746

**Comment by josephfusco** [comment]
Possible regex issue https://github.com/wp-graphql/wpgraphql-ide/pull/88/files

**Comment by josephfusco** [comment]
Consider having versionPlugin.js handle replacing `@since todo` style comments that indicate the next version used should go here. Currently a manual process.

**Comment by josephfusco** [comment]
:github-merged: https://github.com/wp-graphql/wpgraphql-ide/pull/125/files
:arrow_double_down:
:github-merged: https://github.com/wp-graphql/wpgraphql-ide/pull/131
:arrow_double_down:
:package: https://github.com/wp-graphql/wpgraphql-ide/releases/tag/v1.1.7
