### ISSUE TITLE
port `graphiql_router_screens` from core plugin

### ISSUE THREAD

**Issue by josephfusco** [wp-graphql/wpgraphql-ide#27]
## User Story

As a WordPress developer, I would like to be able to actions/filter various parts of the GraphiQL IDE to provide customized functionality.

## Acceptance Criteria

- [ ] new action/filter names is prefixed with `wpgraphqlide_`
- [ ] existing functionality of action/filter is honored
- [ ] ported action/filter is documented

## Reference

- [Core plugin](https://github.com/wp-graphql/wp-graphql)
- [Existing documentation](https://www.wpgraphql.com/docs/customizing-wpgraphiql)

Note that this is unlikely to be ported over considering the latest drawer GUI.

Confirm if that is still the case, even for a dedicated editor page.

**Comment by jasonbahl** [comment]
We're not migrating this JavaScript action from the legacy IDE as the concept of "Screens" isn't coming over in the same way. 

In the legacy IDE we had "Screens" such as "GraphiQL" and "Help":

![CleanShot 2024-03-05 at 12 32 09](https://github.com/wp-graphql/wpgraphql-ide/assets/1260765/6e8ba754-b213-4a95-bc7e-a03686f81864)

![CleanShot 2024-03-05 at 12 30 20](https://github.com/wp-graphql/wpgraphql-ide/assets/1260765/16149cf8-e118-476f-bb18-a220342073bc)

But in the new IDE we're using "Activity Panels" to accomplish the same things. 

![CleanShot 2024-03-05 at 12 32 57](https://github.com/wp-graphql/wpgraphql-ide/assets/1260765/43277465-3b58-4b43-b1eb-c5fdba974680)


There may or may not be similar `doAction` calls added to support the rendering of the Activity Panels but not a 1:1 migration.

**Comment by josephfusco** [comment]
Closing in favor of https://github.com/wp-graphql/wpgraphql-ide/issues/109
