### ISSUE TITLE
port `graphiql_explorer_operation_action_menu_items` from core plugin

### ISSUE THREAD

**Issue by josephfusco** [wp-graphql/wpgraphql-ide#28]
## User Story

As a WordPress developer, I would like to be able to actions/filter various parts of the GraphiQL IDE to provide customized functionality.

## Acceptance Criteria

- [ ] new action/filter names is prefixed with `wpgraphqlide_`
- [ ] existing functionality of action/filter is honored
- [ ] ported action/filter is documented

## Reference

- [Core plugin](https://github.com/wp-graphql/wp-graphql)
- [Existing documentation](https://www.wpgraphql.com/docs/customizing-wpgraphiql)

Note that this one is unlikely to be ported over given the context of the current core implementation. 

Confirm that this is not needed.

**Comment by jasonbahl** [comment]
The legacy IDE had "action menu items" in the Query Composer on each "document" in the IDE. 

These menu items were filterable. 

We've intentionally decided to leave this menu out of the UI so this filter will not be ported to the new WPGraphQL IDE. 

![CleanShot 2024-03-05 at 12 26 38](https://github.com/wp-graphql/wpgraphql-ide/assets/1260765/990d84cd-7f84-4610-b8db-5b2ddc2b679c)

Possibly could be revisited in the future as the new Query Composer gets some iteration, but no immediate plans to support this "action menu" on each operation in the query composer.

**Comment by josephfusco** [comment]
Closing in favor of https://github.com/wp-graphql/wpgraphql-ide/issues/109
