### ISSUE TITLE
Migrate WordPress Actions / Filters ☕️

### ISSUE THREAD

**Issue by jasonbahl** [wp-graphql/wpgraphql-ide#4]
## User Story

As a WordPress developer, I would like to be able to actions/filter various parts of the GraphiQL IDE to provide customized functionality. 

## Acceptance Criteria

- new action/filter names are prefixed with `wpgraphqlide_`

#### JavaScript Filters

- [ ] #40
- [ ] #39
- [x] #38
- [ ] #37
- [ ] #36
- [ ] #35
- [ ] #34
- [ ] #33
- [ ] #32
- [x] #31
- [x] #30
- [x] #29
- [x] #28
- [x] #27

#### JavaScript Action

- [ ] #26
- [x] #25

#### PHP Filters

- [ ] #24
- [x] #23

#### PHP Actions

- [X] #22

Hooks / Filters should be added to the new version with different names to prevent possible conflicts with folks running a plugin that extended the _old_ GraphiQL IDE (i.e. `graphiql_app` -> `graphiql_ide_app`)
  
- [ ] Document how to use these hooks/filters (at minimum in the merged PR that implements it, so we can add the docs to the website or wherever else when appropriate)

### PHP

- `wpgraphqlide_capability_required`
- `wpgraphqlide_enqueue_script`
- `wpgraphqlide_external_fragments`
- `wpgraphqlide_context` (new hook! no existing mapping)

### JavaScript

- `wpgraphqlide_rendered`
- `wpgraphqlide_cleanup` (new hook! no existing mapping)

**Comment by josephfusco** [comment]
Due to architectural limitations of the current GraphiQL IDE, we will not be performing a 1:1 migration as original planned. Instead, we will capture the spirit of these pluggable areas in a new tracking ticket. https://github.com/wp-graphql/wpgraphql-ide/issues/109

Closing this and we continue discussion in #109
