### ISSUE TITLE
Use asset.php to determine version/dependencies

### ISSUE THREAD

**Issue by jasonbahl** [wp-graphql/wpgraphql-ide#43]
When using wp-scripts, it outputs an asset.php for each entry defined in the webpack.config.js (or default single entry if no webpack config is defined). 

This asset.php file contains a dynamic version and also includes all required core wp-* dependencies. 

For example, if we add `const { data } = wp.data;` to one of our components, the asset.php file will now have `wp-data` as a dependency and will have a dynamic version generated which should help bust some asset caches as well.

**Comment by josephfusco** [comment]
WordPress has packages that can used for our use cases instead of relying on the WordPress object being available. This is the gutenberg way.

https://developer.wordpress.org/block-editor/reference-guides/packages/packages-data/

```
import { createReduxStore, register } from '@wordpress/data';
```
