### ISSUE TITLE
Add "Help Page" from the old GraphiQL as a "plugin" in the new GraphiQL

### ISSUE THREAD

**Issue by jasonbahl** [wp-graphql/wpgraphql-ide#51]
The previous GraphiQL had a "help" page that users could click and see links to various resources to get help and read docs, etc. 

![CleanShot 2024-02-28 at 11 19 29](https://github.com/wp-graphql/wpgraphql-ide/assets/1260765/ee7a878f-3b4f-4d73-8c02-0218e472251b)

The functionality is helpful, and I think it should be ported over using the new GraphQL "plugins" concept. 

Similar to clicking "History" / "Docs", and the "plugin panel" shows the active plugin, a "Help" plugin could be added where a button on the sidebar can be clicked and a list of resources could be shown. 

![graphiql-plugins](https://github.com/wp-graphql/wpgraphql-ide/assets/1260765/aeec6368-e9b0-4217-9725-7c7f8d0381e9)

**NOTE**: Tests for the "help" page are already scaffolded in #49 as we had tests for this feature in the previous GraphiQL

**Comment by ChrisWiegman** [comment]
Closed by #61
