### ISSUE TITLE
Toolbar Button Tooltip isn't visible when the IDE is in the drawer

### ISSUE THREAD

**Issue by jasonbahl** [wp-graphql/wpgraphql-ide#52]
When interacting with the IDE as a standalone IDE, the Toolbar Buttons have a tooltip:

![CleanShot 2024-02-28 at 12 16 18](https://github.com/wp-graphql/wpgraphql-ide/assets/1260765/c93c2eb6-ea7a-48e8-82d3-754f9dd9bf51)

But when the IDE is opened in a drawer, the tooltip is not visible. 

![CleanShot 2024-02-28 at 12 17 49](https://github.com/wp-graphql/wpgraphql-ide/assets/1260765/e154f0a0-a461-4c3a-a042-66876fcb877b)

My hunch is a z-index issue, but I've not looked into it. 

----

The same happens with the buttons on the sidebar to open the docs/history, refresh the schema, etc.

**Comment by josephfusco** [comment]
This fix has been added to #47

https://github.com/wp-graphql/wpgraphql-ide/pull/47/commits/0918c8c06fc7c7f189653d8afd50f584952ab8e7
