### ISSUE TITLE
Styles for new IDE are impacting the legacy IDE

### ISSUE THREAD

**Issue by jasonbahl** [wp-graphql/wpgraphql-ide#53]
When the new WPGraphQL IDE plugin is active, the styles impact the legacy IDE. 

Steps to reproduce: 

- With the WPGraphQL IDE plugin **deactivated** the legacy GraphiQL styles look like: 

![CleanShot 2024-02-28 at 12 26 40](https://github.com/wp-graphql/wpgraphql-ide/assets/1260765/a68a5a9b-dcb9-4573-b9a2-3e0e3a036e05)

- With the WPGraphQL IDE plugin **active** the legacy GraphiQL styles look like: 

![CleanShot 2024-02-28 at 12 27 00](https://github.com/wp-graphql/wpgraphql-ide/assets/1260765/7d94c47c-6a8b-46cb-b982-2c03aa1507de)

----

It appears that some styles intended for the new IDE are being enqueued for the page for the old IDE causing this hybrid light/dark mode thing.

**Comment by josephfusco** [comment]
@jasonbahl I could be wrong but this might be due to cached assets as we do not yet have a cache busting mechanism for development

**Comment by josephfusco** [comment]
Accidentally closed as this is still an issue
