### ISSUE TITLE
Formalize `registerToolbarButton` API

### ISSUE THREAD

**Issue by jasonbahl** [wp-graphql/wpgraphql-ide#62]
In #60 we introduced a way to filter buttons into the Button Toolbar. 

I the spirit of other GraphQL / WordPress APIs, it would be nice to formalize this into a `registerToolbarButton` API to reduce friction for developers that want to extend the toolbar. 

As a developer, I would like to be able to do something similar to the following: 

`my-plugin.js`
```js
const { registerToolbarButton } = WPGRAPHQL_IDE;

registerToolbarButton( 'my-button', {
  title: 'My Button',
  description: 'My Button does x, y and z',
  icon: () => {} // name of icon from supported icon library or custom Icon component
  onClick: () => {} // what happens when the button is clicked
} );
```

**Comment by josephfusco** [comment]
Closed by https://github.com/wp-graphql/wpgraphql-ide/releases/tag/v2.0.0
