### ISSUE TITLE
Add comprehensive test for GraphiQL schema docs panel

### ISSUE THREAD

**Issue by jasonbahl** [wp-graphql/wpgraphql-ide#74]
As a maintainer, I'd like to test the ability to access Schema documentation to reference the fields and Types as I compose the query document.

## Acceptance Criteria

- expect hovering a valid field in the document displays a popover
- expect `cmd + click` a field in the query document to open documentation in Docs browser
- expect clicking the docs button opens the Docs browser
- expect clicking the docs button when the Docs browser is open, closes the Docs browser

**Comment by josephfusco** [comment]
Closing in favor of adding directly to AC.
