### ISSUE TITLE
Create test environment for GraphiQL 3 work

### ISSUE THREAD

**Issue by ChrisWiegman** [wp-graphql/wpgraphql-ide#8]
We need to ensure our work on GraphiQL 3 is well-tested and ready for production. This ticket is to create a proper testing environment for the extension.

## Acceptance Criteria

- [x] Github Workflow for unit tests on JS codebase
- [x] GitHub workflow for E2E tests
- [x] A single test of each type (unit and E2E) to ensure all is working

**Comment by jasonbahl** [comment]
The test environments for e2e and unit tests have been scaffolded and run in Github workflows in: https://github.com/wp-graphql/wpgraphql-ide/pull/15

There are currently some failing tests, but those will be addressed as needed as part of #16 as tests are all migrated.
