### ISSUE TITLE
Admin Notices should not show on the standalone GraphiQL IDE page

### ISSUE THREAD

**Issue by jasonbahl** [wp-graphql/wpgraphql-ide#89]
When using the GraphiQL IDE, admin notices should not be displayed. 

In the "legacy" IDE there were styles that hid the notices, but these styles did not get ported over and it leads to a big of a funky experience. 

We _should_ however, see notices registered with `register_graphql_admin_notice` and they should be styled appropriately, matching the experience of the legacy IDE.

![CleanShot 2024-04-03 at 07 15 08](https://github.com/wp-graphql/wpgraphql-ide/assets/1260765/6e2a86b8-a708-4a47-939c-eaeca6f6d0e4)

**Comment by josephfusco** [comment]
Closed by #91 🙌
